name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.10','3.11','3.12', '3.13']

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        cache: 'pip'
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .[dev]
    - name: Test with pytest via tox
      run: |
        tox -e py${{ matrix.python-version }}
    - name: Test with flake8 via tox
      run: |
        tox -e flake8
    - name: Test with mypy via tox
      run: |
        tox -e mypy
    - name: Test with black via tox
      run: |
        tox -e black
